run:
	cargo run -- parse examples/project.txt

tree:
	cargo run -- parse examples/project.txt --tree

format:
	cargo fmt --all

lint:
	cargo clippy 
test:
	cargo test

clean:
	cargo clean

docs:
	cargo doc --no-deps --open

credits:
	cargo run -- credits

